### ISSUE TITLE
Add every missing NNB arcade Nextbots

### ISSUE THREAD

**Issue by Nik0-0** [Nik0-0/nikosnextbots#25]
- [x] Grumbo
- [x] Giggle
- [x] Rei Plush
- [x] Icosahedron
- [x] Leorio
- [x] LolGuy
- [x] Mohu
- [x] Jack
- [x] ~Specimen~ Skipped
- [x] ~Train Griffin~ Skipped
- [x] Unfortunate
# Compatible with Possessor:
- [x] Grumbo
- [x] Giggle
- [x] Rei Plush
- [x] Icosahedron
- [x] Leorio
- [x] LolGuy
- [x] Mohu
- [x] Jack
- [x] ~Specimen~ Skipped
- [x] ~Train Griffin~ Skipped
- [x] Unfortunate

**Comment by Serek-21** [comment]
YEEEEEEEEEEEEEE
